# TMDB API配置
tmdb:
  api_key: "486ceb284a5bba2fb9dff62fb2d2c819"  # TMDB API密钥
  base_url: "https://api.themoviedb.org/3"
  image_base_url: "https://image.tmdb.org/t/p/"
  
  # 网络配置
  timeout: 30        # 请求超时时间(秒)
  max_retries: 5     # 最大重试次数
  retry_delay: 2     # 重试延迟(秒)

# 图片下载配置
crawler:
  download_timeout: 30      # 下载超时时间(秒)
  concurrent_downloads: 3   # 并发下载数量

# InsightFace配置
face_recognition:
  model_name: "buffalo_l"   # 可选: buffalo_s, buffalo_m, buffalo_l
  detection_threshold: 0.6  # 人脸检测阈值
  embedding_dim: 512        # 特征向量维度
  face_alignment: true      # 是否进行人脸对齐
  
# 向量数据库配置
vector_database:
  type: "faiss"            # 可选: faiss, chromadb
  index_type: "Flat"       # Faiss索引类型 (Flat适合小数据量)
  dimension: 512           # 向量维度
  similarity_threshold: 0.8 # 相似度阈值
  
  # ChromaDB配置 (如果选择chromadb)
  chromadb:
    persist_directory: "./data/embeddings/chromadb"
    collection_name: "actor_faces"

# 数据存储配置
storage:
  images_dir: "./data/images"
  embeddings_dir: "./data/embeddings"  
  metadata_dir: "./data/metadata"
  database_file: "./data/metadata/actors.db"

# 去重配置
deduplication:
  face_similarity_threshold: 0.95  # 人脸相似度阈值
  image_hash_threshold: 0.9        # 图片hash相似度阈值
  enable_face_clustering: true     # 是否启用人脸聚类去重

# Web界面配置
web:
  host: "0.0.0.0"
  port: 5000
  debug: true
  
  # 文件上传配置
  upload:
    max_file_size: "2GB"           # 最大文件大小
    allowed_video_formats:         # 支持的视频格式
      - ".mp4"
      - ".avi"
      - ".mov" 
      - ".mkv"
      - ".flv"
      - ".wmv"
    allowed_image_formats:         # 支持的图片格式
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".bmp"
      - ".tiff"

# 视频处理配置
video_processing:
  # 长视频处理优化
  long_video_mode:
    enabled: true                    # 是否自动启用长视频模式
    auto_detect_threshold: 60        # 自动检测阈值（分钟）
    max_memory_usage: 0.8            # 最大内存使用率
    memory_check_interval: 100       # 内存检查间隔（帧数）
    chunk_size: 300                  # 分块处理大小（帧数）
    checkpoint_interval: 1800        # 检查点保存间隔（秒，30分钟）
  
  # 智能跳帧策略
  smart_skip:
    enabled: true                    # 是否启用智能跳帧
    strategy: "duration_based"       # 跳帧策略: duration_based, quality_based, adaptive
    max_skip_rate: 5                 # 最大跳帧率
    quality_threshold: 0.7           # 质量阈值（质量模式下使用）
  
  # 并行处理配置
  parallel_processing:
    enabled: true                    # 是否启用并行处理
    max_workers: 2                   # 最大工作线程数
    queue_size_multiplier: 2         # 队列大小倍数
    timeout_seconds: 2.0             # 队列超时时间
  
  # 性能优化
  performance:
    gc_threshold: 0.8                # 垃圾回收阈值
    frame_compression_enabled: true   # 是否启用帧压缩
    max_frame_size: 1920             # 最大帧尺寸
    batch_processing_size: 10         # 批处理大小

# 日志配置
logging:
  level: "INFO"
  file: "./logs/system.log"
  max_size: "10MB"
  backup_count: 5