crawler:
  concurrent_downloads: 3
  download_timeout: 30
deduplication:
  enable_face_clustering: true
  face_similarity_threshold: 0.95
  image_hash_threshold: 0.9
face_recognition:
  detection_threshold: 0.6
  embedding_dim: 512
  face_alignment: true
  max_faces_per_actor: 20
  min_face_score: 0.8
  model_name: buffalo_l
logging:
  backup_count: 5
  file: D:\DEVELOPE\Actor_dataset_contruct\logs\system.log
  level: INFO
  max_size: 10MB
storage:
  database_file: ./data/metadata/actors.db
  embeddings_dir: D:\DEVELOPE\Actor_dataset_contruct\data\embeddings
  images_dir: D:\DEVELOPE\Actor_dataset_contruct\data\images
  metadata_dir: D:\DEVELOPE\Actor_dataset_contruct\data\metadata
tmdb:
  api_key: your_tmdb_api_key_here
  base_url: https://api.tmdb.org/3
  image_base_url: https://image.tmdb.org/t/p/
  max_retries: 5
  retry_delay: 2
  timeout: 30
vector_database:
  chromadb:
    collection_name: actor_faces
    persist_directory: ./data/embeddings/chromadb
  dimension: 512
  index_type: Flat
  similarity_threshold: 0.8
  type: faiss
video_processing:
  long_video_mode:
    auto_detect_threshold: 60
    checkpoint_interval: 1800
    chunk_size: 300
    enabled: true
    max_memory_usage: 0.8
    memory_check_interval: 100
  parallel_processing:
    enabled: true
    max_workers: 2
    queue_size_multiplier: 2
    timeout_seconds: 2.0
  performance:
    batch_processing_size: 10
    frame_compression_enabled: true
    gc_threshold: 0.8
    max_frame_size: 1920
  smart_skip:
    enabled: true
    max_skip_rate: 5
    quality_threshold: 0.7
    strategy: duration_based
web:
  debug: true
  host: 0.0.0.0
  port: 5000
  upload:
    allowed_image_formats:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .tiff
    allowed_video_formats:
    - .mp4
    - .avi
    - .mov
    - .mkv
    - .flv
    - .wmv
    max_file_size: 2GB
